version: '3.7'
services:
  php:
    container_name: webschool_php
    build: .
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - .:/var/www/html
    links:
     - mysql
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal

  php-unit:
    build: .
    volumes:
     - .:/var/www/html
    environment:
      - XDEBUG_MODE=coverage
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=0
      - XDEBUG_SESSION=default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "true"

  mysql:
    container_name: webschool_mysql
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
     - MYSQL_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=webschool

volumes:
  dbdata: